swagger: true

path:
#  log_folder: "/home/jianfengye/hade/log/"
#  runtime_folder: "/home/jianfengye/hade/runtime/"

dev: # 调试模式
    port: 8070 # 调试模式最终监听的端口，默认为8070
    backend: # 后端调试模式配置
        refresh_time: 3  # 调试模式后端更新时间，如果文件变更，等待3s才进行一次更新，能让频繁保存变更更为顺畅, 默认1s
        port: 8072 # 后端监听端口，默认8072
        monitor_folder: "" # 监听文件夹地址，为空或者不填默认为AppFolder
    frontend: # 前端调试模式配置
        port: 8071 # 前端监听端口, 默认8071
